swagger: '2.0'
schemes:
    - https
host: localhost
basePath: /api

consumes: [application/json]
produces: [application/json]

info:
    title: 'astrack api'
    version: 1.0.0
tags:
  - name: user
    description: User operations
  - name: activity
    description: Activity management

paths:
    /users/singup:
        post:
            tags: [user]
            summary: Sign up
            operationId: userSignUp
            parameters:
              - in: body
                name: body
                schema:
                    type: object
                    required: [username, password]
                    properties:
                        username:
                            type: string
                        password:
                            type: string
                    example:
                        username: fubar
                        password: catKeyboard
            responses:
                '201':
                    description: 'Created'
                    schema:
                        type: object
                        properties:
                            user:
                                $ref: '#/definitions/User'
                    examples:
                        application/json:
                            user:
                                username: fubar
                '400':
                    $ref: '#/responses/InvalidInput'
                '422':
                    description: 'Username is taken'
                    schema:
                        $ref: '#/definitions/GenericError'
                    examples:
                        application/json:
                            error: username_is_taken
    /users/signin:
        post:
            tags: [user]
            summary: Sign in
            operationId: userSignIn
            parameters:
              - in: body
                name: body
                schema:
                    type: object
                    required: [username, password]
                    properties:
                        username:
                            type: string
                        password:
                            type: string
            responses:
                '200':
                    description: 'Signed in'
                    schema:
                        type: object
                        properties:
                            user:
                                $ref: '#/definitions/User'
                    examples:
                        application/json:
                            user:
                                username: fubar
                '404':
                    $ref: '#/responses/NotFound'
    /users/signout:
        post:
            tags: [user]
            summary: Sign out
            operationId: userSignOut
            responses:
                '200':
                    description: 'Signed out'
                    examples:
                        application/json:

                '403':
                    description: 'Not signed in'
                    schema:
                        $ref: '#/definitions/GenericError'
                    examples:
                        application/json:
                            error: not_signed_in

    /users/me:
        get:
            tags: [user]
            summary: Get current user
            operationId: userGetMe
            responses:
                '200':
                    schema:
                        type: object
                        properties:
                            user:
                                $ref: '#/definitions/User'
                    examples:
                        application/json:
                            user:
                                username: fubar

    /activities:
        get:
            tags: [activity]
            summary: Get activities
            operationId: activityIndex
            responses:
                '200':
                    schema:
                        type: object
                        properties:
                            tracks:
                                type: array
                                items:
                                    $ref: '#/definitions/Activity'
        post:
            tags: [activity]
            summary: Create activity
            operationId: activityNew
            parameters:
              - in: body
                name: body
                required: true
                schema:
                    type: object
                    required: [activity]
                    properties:
                        name:
                            type: string
            responses:
                '200':
                    schema:
                        type: object
                        properties:
                            activity:
                                $ref: '#/definitions/Activity'
                '400':
                    description: 'Invalid activity'

    /activities/{activityId}:
        delete:
            tags: [activity]
            summary: Delete activity
            operationId: activityDelete
            parameters:
              - in: path
                name: activityId
                type: number
            responses:
                '200':
                    description: 'Deleted'

    /activities/{activityId}/logs:
        post:
            tags: [activity]
            summary: Create activity log
            operationId: activityLogNew
            parameters:
              - in: path
                name: activityId
                type: number
              - in: body
                name: body
                required: true
                schema:
                    type: object
                    required: [date, duration]
                    properties:
                        date:
                            type: number
                        duration:
                            type: number

    /activities/{activityId}/logs/{logId}:
        delete:
            tags: [activity]
            summary: Delete activity log
            operationId: activityLogDelete
            parameters:
              - in: path
                name: activityId
                type: number
              - in: path
                name: logId
                type: number
            responses:
                '200':
                    description: 'Deleted'

responses:
    NotFound:
        description: Entity not found
        schema:
            $ref: '#/definitions/GenericError'
        examples:
            application/json:
                error: not_found
    InvalidInput:
        description: Invalid input for operation
        schema:
            $ref: '#/definitions/InvalidInputError'
        examples:
            application/json:
                error: invalid_input
                paths:
                  - path: username
                    constraint: cannot_be_empty

definitions:
    User:
        type: object
        properties:
            username:
                type: string
    Activity:
        type: object
        properties:
            id:
                type: number
            name:
                type: string
            logs:
                type: array
                items:
                    type: object
                    properties:
                        id:
                            type: string
                        summary:
                            type: string
                        date:
                            type: number
                        duration:
                            type: number
    GenericError:
        type: object
        properties:
            error:
                type: string
    InvalidInputError:
        type: object
        properties:
            error:
                type: string
            paths:
                type: array
                items:
                    type: object
                    properties:
                        path:
                            type: string
                        constraint:
                            type: string